baseURL = "/"
title = "MocaccinoOS"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]


# Highlighting config
pygmentsCodeFences = true
#pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
#pygmentsUseClassic = false
pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "native"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "MocaccinoOS"
description = "what's after a good Sabayon?"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Everything below this are Site Params

[params]
copyright = "MocaccinoOS org."
privacy_policy = ""

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "main"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://www.mocaccino.org"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/MocaccinoOS/website"

github_subdir = ""

# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/MocaccinoOS"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true


# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/MocaccinoOS/website/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/MocaccinoOS/website/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/MocaccinoOS"
	icon = "fab fa-github"
    desc = "Development takes place here!"
[[params.links.user]]
	name = "Forum"
	url = "https://github.com/mocaccinoOS/mocaccino/discussions"
	icon = "fab fa-discourse"
    desc = "Join our community in the Forum!"

[[params.links.user]]
	name = "Telegram"
	url = "https://t.me/mocaccinoOS"
	icon = "fab fa-telegram"
        desc = "Join us on the official Telegram group!"

[[params.links.user]]
	name = "Twitter"
	url = "https://twitter.com/MocaccinoOs"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter!"

[[params.links.user]]
        name = "Matrix chat"
        url = "https://matrix.to/#/#mocaccinoOS:matrix.org"
        icon = "fas fa-comments"
        desc = "Chat with other project users"

[[params.links.user]]
        name = "Signal chat"
        url = "https://signal.group/#CjQKIJ7Faj4or6bTZtRDJEzqTPC-DFEtEjhnStePhXS-LPETEhBlAPIS7UPGRK-8SUSMMrm6"
        icon = "fas fa-comments"
        desc = "Join us on the official Signal group!"

[[params.links.developer]]
	name = "Slack"
	url = "https://join.slack.com/t/luet/shared_invite/enQtOTQxMjcyNDQ0MDUxLWQ5ODVlNTI1MTYzNDRkYzkyYmM1YWE5YjM0NTliNDEzNmQwMTkxNDRhNDIzM2Y5NDBlOTZjZTYxYWQyNDE4YzY"
	icon = "fab fa-slack"
        desc = "Join the development channel on slack"

[[menu.main]]
    name = "Packages"
    weight = 50
    url = "https://packages.mocaccino.org"

[[menu.main]]
    name = "Issue tracker"
    weight = 10
    url = "https://github.com/mocaccinoOS/mocaccino/issues"
